import { Expense } from '@/types';
import { format } from 'date-fns';

export function generateExpenseMarkdown(expense: Expense): string {
  return `
# Expense Memory: ${expense.location || 'Unknown Location'}
Date: ${format(new Date(expense.createdAt), 'yyyy-MM-dd HH:mm')}
Category: ${expense.category}
Amount: ${new Intl.NumberFormat('vi-VN').format(expense.amount)} VND
Mood: ${expense.mood}

## Caption
${expense.aiSummary || 'No caption generated.'}

## Note
${expense.note || 'No additional notes.'}

## Metadata
- Wallet ID: ${expense.walletId}
- ID: ${expense.id}
- Image: ${expense.imageUrl || 'No image'}

---
Generated by MoneyMemory AI
`;
}

/**
 * In a real production app, this function would call the Google Drive API
 * to upload the markdown file.
 */
export async function syncToGoogleDrive(expense: Expense) {
  const content = generateExpenseMarkdown(expense);
  const fileName = `expense_${expense.id}.md`;
  
  console.log(`Syncing ${fileName} to Google Drive...`);
  // Implementation using googleapis or a custom API route
  // return fetch('/api/sync/drive', { method: 'POST', body: JSON.stringify({ fileName, content }) });
}
